name: Test

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!uat'
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: yarn -i
      - name: Run Tests
        run: yarn test
    