name: Deploy

on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "food-app-frontend-uat"
          heroku_email: "xhe123@hotmail.co.uk"
